### ISSUE TITLE
Regarding Question 2

### ISSUE THREAD

**Issue by Shrimat** [harrisonzhu508/math40012#1]
Hi,

Could you just give a mark breakdown for Q2 on the test? I can't find a mark scheme for this on Blackboard so it would be useful to have a model answer.

Thanks!

**Comment by harrisonzhu508** [comment]
@Shrimat Sorry I don't have the markscheme or the question paper at the moment, I will aim to get back to you on this as soon as possible.

**Comment by harrisonzhu508** [comment]
@Shrimat this is now uploaded to ~/Course Materials - Applied Mathematical Methods/Tests

**Comment by Shrimat** [comment]
@harrisonzhu508 Thanks for this!
